version: "3.3"

services:

  mongodb:
    image: mongo:4.4.12
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./.mongodb/data/db/:/data/db/
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017
    restart: on-failure
  
  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - cache:/data 

  app:
    build: .
    container_name: chefeed-api
    volumes:
      - .:/src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    restart: on-failure

volumes:
  cache:
    driver: local
